---
booktitle: Proceedings of the Innovation and Responsibility in AI-Supported Education
  Workshop
shortname: iRAISE
volume: '273'
year: '2025'
start: &1 2025-03-03
end: 2025-03-03
published: 2025-03-31
sections:
- name: Spotlight
  title: Spotlight
- name: Poster
  title: Poster
layout: proceedings
series: Proceedings of Machine Learning Research
publisher: PMLR
issn: 2640-3498
id: iRAISE-2025
month: 0
cycles: false
bibtex_editor: Wang, Zichao and Woodhead, Simon and Ananda, Muktha and Mallick, Debshila
  Basu and Sharpnack, James and Burstein, Jill
editor:
- given: Zichao
  family: Wang
- given: Simon
  family: Woodhead
- given: Muktha
  family: Ananda
- given: Debshila Basu
  family: Mallick
- given: James
  family: Sharpnack
- given: Jill
  family: Burstein
title: Proceedings of Machine Learning Research
description: |
  Proceedings of the Innovation and Responsibility in AI-Supported Education Workshop
    Held in Philadelphia, Pennsylvania, USA on 03 March 2025

  Published as Volume 273 by the Proceedings of Machine Learning Research on 31 March 2025.

  Volume Edited by:
    Zichao Wang
    Simon Woodhead
    Muktha Ananda
    Debshila Basu Mallick
    James Sharpnack
    Jill Burstein

  Series Editors:
    Neil D. Lawrence
date_str: 03 Mar
url: https://proceedings.mlr.press
author:
  name: PMLR
baseurl: "/v273"
twitter_username: MLResearchPress
github_username: mlresearch
markdown: kramdown
exclude:
- README.md
- Gemfile
- ".gitignore"
plugins:
- jekyll-feed
- jekyll-seo-tag
- jekyll-remote-theme
remote_theme: mlresearch/jekyll-theme
style: pmlr
permalink: "/:title.html"
ghub:
  edit: true
  repository: v273
display:
  copy_button:
    bibtex: true
    endnote: true
    apa: true
  comments: false
volume_type: Volume
volume_dir: v273
email: ''
conference:
  name: Innovation and Responsibility in AI-Supported Education
  url: https://iraise-25-aaai.my.canva.site/
  location: Philadelphia, Pennsylvania, USA
  dates:
  - *1
analytics:
  google:
    tracking_id: UA-92432422-1
link_visibility:
  openreview: true
  pdf: true
  supplementary: true
  software: true
  video: true
  arxiv: true
  doi: true
  website: true
orig_bibfile: "/Users/neil/mlresearch/v273/v273.bib"
# Site settings
# Original source:  /Users/neil/mlresearch/v273/v273.bib
